<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="51260" started-at="2021-05-06T23:48:37 IST" finished-at="2021-05-06T23:49:28 IST">
    <groups>
    </groups>
    <test name="testfour" duration-ms="10805" started-at="2021-05-06T23:48:37 IST" finished-at="2021-05-06T23:48:48 IST">
      <class name="tests.TestFour">
        <test-method status="PASS" signature="testfour()[pri:0, instance:tests.TestFour@2bbf4b8b]" name="testfour" duration-ms="10758" started-at="2021-05-06T23:48:37 IST" finished-at="2021-05-06T23:48:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testfour -->
      </class> <!-- tests.TestFour -->
    </test> <!-- testfour -->
    <test name="testtwo" duration-ms="13157" started-at="2021-05-06T23:48:37 IST" finished-at="2021-05-06T23:48:50 IST">
      <class name="tests.Testtwo">
        <test-method status="PASS" signature="testtwo()[pri:0, instance:tests.Testtwo@63440df3]" name="testtwo" duration-ms="13111" started-at="2021-05-06T23:48:37 IST" finished-at="2021-05-06T23:48:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testtwo -->
      </class> <!-- tests.Testtwo -->
    </test> <!-- testtwo -->
    <test name="testthree" duration-ms="13163" started-at="2021-05-06T23:48:37 IST" finished-at="2021-05-06T23:48:50 IST">
      <class name="tests.TestThree">
        <test-method status="PASS" signature="testthree()[pri:0, instance:tests.TestThree@7a3d45bd]" name="testthree" duration-ms="13113" started-at="2021-05-06T23:48:37 IST" finished-at="2021-05-06T23:48:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testthree -->
      </class> <!-- tests.TestThree -->
    </test> <!-- testthree -->
    <test name="logintest" duration-ms="51259" started-at="2021-05-06T23:48:37 IST" finished-at="2021-05-06T23:49:28 IST">
      <class name="tests.logintest">
        <test-method status="PASS" signature="openapplication()[pri:0, instance:tests.logintest@462d5aee]" name="openapplication" is-config="true" duration-ms="11391" started-at="2021-05-06T23:48:37 IST" finished-at="2021-05-06T23:48:48 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapplication -->
        <test-method status="FAIL" signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:tests.logintest@462d5aee]" name="login" duration-ms="16937" started-at="2021-05-06T23:48:48 IST" data-provider="getlogindata" finished-at="2021-05-06T23:49:05 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[arun.selenium@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Second@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[successful]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [successful] but found [failure]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [successful] but found [failure]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at tests.logintest.login(logintest.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="closure()[pri:0, instance:tests.logintest@462d5aee]" name="closure" is-config="true" duration-ms="105" started-at="2021-05-06T23:49:05 IST" finished-at="2021-05-06T23:49:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
        <test-method status="PASS" signature="openapplication()[pri:0, instance:tests.logintest@462d5aee]" name="openapplication" is-config="true" duration-ms="5773" started-at="2021-05-06T23:49:05 IST" finished-at="2021-05-06T23:49:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openapplication -->
        <test-method status="PASS" signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:tests.logintest@462d5aee]" name="login" duration-ms="16907" started-at="2021-05-06T23:49:11 IST" data-provider="getlogindata" finished-at="2021-05-06T23:49:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[dummy@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dummy]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[failure]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="closure()[pri:0, instance:tests.logintest@462d5aee]" name="closure" is-config="true" duration-ms="95" started-at="2021-05-06T23:49:28 IST" finished-at="2021-05-06T23:49:28 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- tests.logintest -->
    </test> <!-- logintest -->
  </suite> <!-- Suite -->
</testng-results>
